// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeWendys.Models;

namespace PrimeWendys.Models.Migrations
{
    [DbContext(typeof(PrimeWendysDB))]
    partial class PrimeWendysDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrimeWendys.Models.Door", b =>
                {
                    b.Property<int>("Door_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Door_Picture");

                    b.Property<double>("Door_Price");

                    b.Property<string>("Door_Type");

                    b.Property<int?>("Wendy_Id");

                    b.HasKey("Door_Id");

                    b.HasIndex("Wendy_Id");

                    b.ToTable("DOOR");
                });

            modelBuilder.Entity("PrimeWendys.Models.Permission", b =>
                {
                    b.Property<int>("Per_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Role_Id");

                    b.HasKey("Per_Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("PERMISSION");
                });

            modelBuilder.Entity("PrimeWendys.Models.Role", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("User_Id");

                    b.HasKey("Role_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("ROLE");
                });

            modelBuilder.Entity("PrimeWendys.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("DoB");

                    b.Property<string>("Email");

                    b.Property<string>("First_Name");

                    b.Property<string>("Home_Address");

                    b.Property<string>("Last_Name");

                    b.Property<string>("Password");

                    b.Property<string>("State");

                    b.Property<int>("Zip_Code");

                    b.HasKey("User_Id");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("PrimeWendys.Models.Wendy", b =>
                {
                    b.Property<int>("Wendy_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumOfRooms");

                    b.Property<byte[]>("Picture");

                    b.Property<double>("Price");

                    b.Property<string>("Size");

                    b.Property<int?>("User_Id");

                    b.Property<double>("Wendy_Type");

                    b.Property<int>("Wood_Id");

                    b.HasKey("Wendy_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("Wood_Id")
                        .IsUnique();

                    b.ToTable("WENDY");
                });

            modelBuilder.Entity("PrimeWendys.Models.Window", b =>
                {
                    b.Property<int>("Win_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Wendy_Id");

                    b.Property<byte[]>("Win_Picture");

                    b.Property<double>("Win_Price");

                    b.Property<string>("Win_Type");

                    b.HasKey("Win_Id");

                    b.HasIndex("Wendy_Id");

                    b.ToTable("WINDOW");
                });

            modelBuilder.Entity("PrimeWendys.Models.Wood", b =>
                {
                    b.Property<int>("Wood_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Wood_Desc");

                    b.Property<byte[]>("Wood_Picture");

                    b.Property<double>("Wood_Price");

                    b.Property<string>("Wood_Type");

                    b.HasKey("Wood_Id");

                    b.ToTable("WOOD");
                });

            modelBuilder.Entity("PrimeWendys.Models.Door", b =>
                {
                    b.HasOne("PrimeWendys.Models.Wendy", "Wendy")
                        .WithMany()
                        .HasForeignKey("Wendy_Id");
                });

            modelBuilder.Entity("PrimeWendys.Models.Permission", b =>
                {
                    b.HasOne("PrimeWendys.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimeWendys.Models.Role", b =>
                {
                    b.HasOne("PrimeWendys.Models.User", "User")
                        .WithMany("Role")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimeWendys.Models.Wendy", b =>
                {
                    b.HasOne("PrimeWendys.Models.User")
                        .WithMany("Wendys")
                        .HasForeignKey("User_Id");

                    b.HasOne("PrimeWendys.Models.Wood", "Wood")
                        .WithOne("Wendy")
                        .HasForeignKey("PrimeWendys.Models.Wendy", "Wood_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimeWendys.Models.Window", b =>
                {
                    b.HasOne("PrimeWendys.Models.Wendy", "Wendy")
                        .WithMany()
                        .HasForeignKey("Wendy_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
